# Generated by Django 2.2.7 on 2019-11-26 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Approaches',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Chasing',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Climbing',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Eating',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Foraging',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Indifferent',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Kuks',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Moans',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Other_Activities',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Primary_fur_color',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Quaas',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Running',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Runs_from',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Shift',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Specific_location',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Tail_flags',
        ),
        migrations.RemoveField(
            model_name='squirrels',
            name='Tail_twitches',
        ),
    ]
