# Generated by Django 2.2.7 on 2019-12-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrels',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Unique_Squirrel_ID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=200, primary_key=True, serialize=False),
        ),
    ]
