# Generated by Django 2.2.7 on 2019-11-26 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191126_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Latitude',
            field=models.DecimalField(decimal_places=13, help_text='Latitude', max_digits=20, max_length=200),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Longitude',
            field=models.DecimalField(decimal_places=13, help_text='Longitude', max_digits=20, max_length=200),
        ),
    ]
