# Generated by Django 2.2.7 on 2019-12-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20191201_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrels',
            name='Primary_fur_color',
            field=models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], default='gray', help_text='Primary Fur Color', max_length=200),
        ),
        migrations.AlterField(
            model_name='squirrels',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=200),
        ),
    ]
